/*
 * Adyen Wherever People Pay
 * This is the Adyen API Playground where you can test our API's. <br /><br />You can find out more about Adyen      at <a href=\"http://www.adyen.com\">http://www.adyen.com</a>.  <!--For this sample, you can use the api key \"special-key\" to test the authorization filters.-->
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * FraudCheckResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-16T14:22:24.496+01:00")
public class FraudCheckResult {
  @SerializedName("name")
  private String name = null;

  @SerializedName("accountScore")
  private Integer accountScore = null;

  @SerializedName("checkId")
  private Integer checkId = null;

  public FraudCheckResult name(String name) {
    this.name = name;
    return this;
  }

   /**
   * the name of the risk check
   * @return name
  **/
  @ApiModelProperty(value = "the name of the risk check")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FraudCheckResult accountScore(Integer accountScore) {
    this.accountScore = accountScore;
    return this;
  }

   /**
   * the fraud score generated by the risk check
   * @return accountScore
  **/
  @ApiModelProperty(value = "the fraud score generated by the risk check")
  public Integer getAccountScore() {
    return accountScore;
  }

  public void setAccountScore(Integer accountScore) {
    this.accountScore = accountScore;
  }

  public FraudCheckResult checkId(Integer checkId) {
    this.checkId = checkId;
    return this;
  }

   /**
   * the id of the risk check
   * @return checkId
  **/
  @ApiModelProperty(value = "the id of the risk check")
  public Integer getCheckId() {
    return checkId;
  }

  public void setCheckId(Integer checkId) {
    this.checkId = checkId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FraudCheckResult fraudCheckResult = (FraudCheckResult) o;
    return Objects.equals(this.name, fraudCheckResult.name) &&
        Objects.equals(this.accountScore, fraudCheckResult.accountScore) &&
        Objects.equals(this.checkId, fraudCheckResult.checkId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, accountScore, checkId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FraudCheckResult {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    accountScore: ").append(toIndentedString(accountScore)).append("\n");
    sb.append("    checkId: ").append(toIndentedString(checkId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

