/*
 * Adyen Wherever People Pay
 * This is the Adyen API Playground where you can test our API's. <br /><br />You can find out more about Adyen      at <a href=\"http://www.adyen.com\">http://www.adyen.com</a>.  <!--For this sample, you can use the api key \"special-key\" to test the authorization filters.-->
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ModificationResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-16T14:22:24.496+01:00")
public class ModificationResult {
  @SerializedName("pspReference")
  private String pspReference = null;

  /**
   * the response which indicates if the modification request has been received for processing.
   */
  public enum ResponseEnum {
    @SerializedName("[capture-received]")
    CAPTURE_RECEIVED_("[capture-received]"),
    
    @SerializedName("[cancel-received]")
    CANCEL_RECEIVED_("[cancel-received]"),
    
    @SerializedName("[refund-received]")
    REFUND_RECEIVED_("[refund-received]"),
    
    @SerializedName("[captureOrRefund-received]")
    CAPTUREORREFUND_RECEIVED_("[captureOrRefund-received]");

    private String value;

    ResponseEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("response")
  private ResponseEnum response = null;

  @SerializedName("additionalData")
  private String additionalData = null;

  public ModificationResult pspReference(String pspReference) {
    this.pspReference = pspReference;
    return this;
  }

   /**
   * the unique identifier assigned to this modification.
   * @return pspReference
  **/
  @ApiModelProperty(value = "the unique identifier assigned to this modification.")
  public String getPspReference() {
    return pspReference;
  }

  public void setPspReference(String pspReference) {
    this.pspReference = pspReference;
  }

  public ModificationResult response(ResponseEnum response) {
    this.response = response;
    return this;
  }

   /**
   * the response which indicates if the modification request has been received for processing.
   * @return response
  **/
  @ApiModelProperty(value = "the response which indicates if the modification request has been received for processing.")
  public ResponseEnum getResponse() {
    return response;
  }

  public void setResponse(ResponseEnum response) {
    this.response = response;
  }

  public ModificationResult additionalData(String additionalData) {
    this.additionalData = additionalData;
    return this;
  }

   /**
   * a map of name/value pairs for passing back additional / industry-specific data
   * @return additionalData
  **/
  @ApiModelProperty(value = "a map of name/value pairs for passing back additional / industry-specific data")
  public String getAdditionalData() {
    return additionalData;
  }

  public void setAdditionalData(String additionalData) {
    this.additionalData = additionalData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModificationResult modificationResult = (ModificationResult) o;
    return Objects.equals(this.pspReference, modificationResult.pspReference) &&
        Objects.equals(this.response, modificationResult.response) &&
        Objects.equals(this.additionalData, modificationResult.additionalData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pspReference, response, additionalData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModificationResult {\n");
    
    sb.append("    pspReference: ").append(toIndentedString(pspReference)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    additionalData: ").append(toIndentedString(additionalData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

