/*
 * Adyen Wherever People Pay
 * This is the Adyen API Playground where you can test our API's. <br /><br />You can find out more about Adyen      at <a href=\"http://www.adyen.com\">http://www.adyen.com</a>.  <!--For this sample, you can use the api key \"special-key\" to test the authorization filters.-->
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RecurringDetail;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.LocalDate;

/**
 * RecurringDetailsResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-16T14:22:24.496+01:00")
public class RecurringDetailsResult {
  @SerializedName("creationDate")
  private LocalDate creationDate = null;

  @SerializedName("shopperReference")
  private String shopperReference = null;

  @SerializedName("details")
  private List<RecurringDetail> details = null;

  @SerializedName("lastKnownShopperEmail")
  private String lastKnownShopperEmail = null;

  public RecurringDetailsResult creationDate(LocalDate creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * the creation date when the shopper record was created
   * @return creationDate
  **/
  @ApiModelProperty(value = "the creation date when the shopper record was created")
  public LocalDate getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(LocalDate creationDate) {
    this.creationDate = creationDate;
  }

  public RecurringDetailsResult shopperReference(String shopperReference) {
    this.shopperReference = shopperReference;
    return this;
  }

   /**
   * the reference you use to uniquely identify the shopper (e.g. user ID or account ID)
   * @return shopperReference
  **/
  @ApiModelProperty(value = "the reference you use to uniquely identify the shopper (e.g. user ID or account ID)")
  public String getShopperReference() {
    return shopperReference;
  }

  public void setShopperReference(String shopperReference) {
    this.shopperReference = shopperReference;
  }

  public RecurringDetailsResult details(List<RecurringDetail> details) {
    this.details = details;
    return this;
  }

  public RecurringDetailsResult addDetailsItem(RecurringDetail detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<RecurringDetail>();
    }
    this.details.add(detailsItem);
    return this;
  }

   /**
   * a list of one or more recurring payment details
   * @return details
  **/
  @ApiModelProperty(value = "a list of one or more recurring payment details")
  public List<RecurringDetail> getDetails() {
    return details;
  }

  public void setDetails(List<RecurringDetail> details) {
    this.details = details;
  }

  public RecurringDetailsResult lastKnownShopperEmail(String lastKnownShopperEmail) {
    this.lastKnownShopperEmail = lastKnownShopperEmail;
    return this;
  }

   /**
   * the most recent email for this shopper (if available)
   * @return lastKnownShopperEmail
  **/
  @ApiModelProperty(value = "the most recent email for this shopper (if available)")
  public String getLastKnownShopperEmail() {
    return lastKnownShopperEmail;
  }

  public void setLastKnownShopperEmail(String lastKnownShopperEmail) {
    this.lastKnownShopperEmail = lastKnownShopperEmail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecurringDetailsResult recurringDetailsResult = (RecurringDetailsResult) o;
    return Objects.equals(this.creationDate, recurringDetailsResult.creationDate) &&
        Objects.equals(this.shopperReference, recurringDetailsResult.shopperReference) &&
        Objects.equals(this.details, recurringDetailsResult.details) &&
        Objects.equals(this.lastKnownShopperEmail, recurringDetailsResult.lastKnownShopperEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDate, shopperReference, details, lastKnownShopperEmail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecurringDetailsResult {\n");
    
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    shopperReference: ").append(toIndentedString(shopperReference)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    lastKnownShopperEmail: ").append(toIndentedString(lastKnownShopperEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

